name: amd64-build
on:
  push:
    branches:
      - main

env:
  BUILDKIT_IMAGE: jkaninda/laravel-php-fpm
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 7.4
        uses: docker/build-push-action@v3
        with:
          file: "./docker/7.4/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:7.4"
      -
        name: Build and push 8.0
        uses: docker/build-push-action@v3
        with:
          file: "./docker/8.0/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:8.0"
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          file: "./docker/8.1/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:8.1"
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v3
        with:
          file: "./docker/8.2/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:8.2"