name: amd64-build
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - closed
    branches:
      - '**'

env:
  BUILDKIT_IMAGE: jkaninda/laravel-php-fpm
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: "./docker/amd64/8.1/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:8.1-test"