name: Build arm

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker build tag'
        required: true
        default: 'latest' 
        type: string

env:
  BUILDKIT_IMAGE: jkaninda/laravel-php-fpm
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          #context: .
          file: "./docker/8.1/Dockerfile"
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:8.1-test"